default['play_app']['install_dir'] = "/opt/coolestprojects"
default['play_app']['dist_url'] = ""
default['play_app']['dist_local_file_path'] = ""
default['play_app']['use_local_dist'] = "false"
default['play_app']['app_dir'] = ''
default['play_app']['config_dir'] = 'config'
default['play_app']['vm_options']='-J-Xms512M -J-Xmx1024M -J-Xss1M'
default['play_app']['pid_file_path']="/var/run/play.pid"
default['play_app']['application_secret_key']="Your Secret Key here"
default['play_app']['play_log_level']="INFO"  
default['play_app']['app_log_level']="DEBUG"
default['play_app']['play_log_dir']="/var/log/"
default['play_app']['max_logging_history']="10"
default['play_app']['language']="en"
default['play_app']['port']="9000" 
default['play_app']['override_config'] = {}
default['play_app']['app_version'] = ""
